Candidate_Search()
{
 

	web_set_sockets_option("SSL_VERSION", "2&3");
 
 

	lr_start_transaction("1_Candidate Search");



	web_url("candidate", 
		"URL=https://staff.belflex.com//Search/candidate/", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Recruiter/", 
		"Snapshot=t124.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/Mvc/Content/amd-base-url-marker.js", ENDITEM, 
		"Url=/Mvc/Content/js/Base/koBindings.js", ENDITEM, 
		"Url=/Mvc/Content/js/Base/cooltipKoBridge.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/Ace/bundles-config.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/Knockout/knockout-3.1.0.debug.js", ENDITEM, 
		"Url=/Mvc/Content/js/Base/tableSorter.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/Rx/main.js", ENDITEM, 
		"Url=/Mvc/Content/js/common.js", ENDITEM, 
		"Url=/Mvc/Content/js/Localization/LocalizationService.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/SearchPage.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/Tipped.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/Rx/rx.min.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/Rx/rx.time.min.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/Rx/rx.dom.min.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/Rx/rx.binding.min.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/globalization/main.js", ENDITEM, 
		"Url=/Mvc/Content/js/Utils/internationalization.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/requirejs-plugins/json.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/moment/moment.min.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/LinqJS/linq.min.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/accounting/accounting.min.js", ENDITEM, 
		"Url=/Mvc/Content/js/Base/api.js", ENDITEM, 
		"Url=/Mvc/Content/js/Base/seq.js", ENDITEM, 
		"Url=/Mvc/Content/js/Base/keys.js", ENDITEM, 
		"Url=/Mvc/Content/js/Base/dynamic.js", ENDITEM, 
		"Url=/Mvc/Content/js/Base/userSettings.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/SearchResults.js", ENDITEM, 
		"Url=/Mvc/Content/js/Frame/container.js", ENDITEM, 
		"Url=/Mvc/Content/require/css.min.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/globalization/globalize.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/globalization/globalize/number.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/Kendo/styles/kendo.common.min.css", ENDITEM, 
		"Url=/Mvc/Content/css/Library/library.min.css", ENDITEM, 
		"Url=/Mvc/Content/css/erecruit.css", ENDITEM, 
		"Url=/Mvc/Content/js/External/Kendo/styles/kendo.uniform.min.css", ENDITEM, 
		"Url=/Mvc/Content/js/External/globalization/globalize/currency.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/globalization/globalize/date.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/globalization/globalize/plural.js", ENDITEM, 
		"Url=/Mvc/Content/require/text.js", ENDITEM, 
		"Url=/Mvc/Content/js/Base/autobind.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/InfoBox.js", ENDITEM, 
		"Url=/Mvc/Localization/LocalizationModel", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/Help.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/interfaces.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/globalization/cldr.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/LiveFilterService.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Criterion.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/globalization/cldr/event.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/globalization/cldr/supplemental.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/Base.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/stylesheet.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/Kendo/js-debug/kendo.web.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/Popup.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/Select.js", ENDITEM, 
		"Url=/Mvc/Content/js/Base/dataSource.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Components/SidebarButtonsTab.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/FtsFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Components/Columns.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/Status.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Tags/Filter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Daxtra/DaxtraFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/TextFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Recruiter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/DateRangeFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/CheckboxFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/OwnershipMaintenanceTypeFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/OwnerExpirationFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/AdSource.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Candidate/Candidate.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Location.js", ENDITEM, 
		"Url=/Mvc/Content/js/Forms/Search/filter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Match/Match.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/DateFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Templates/Location.SearchFilter.css", ENDITEM, 
		"Url=/Mvc/Content/js/Forms/Search/Templates/filter.css", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Skill/SkillsFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Candidate/RequirementsFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Candidate/AssessmentsFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/PastStatusFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/FlagListFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/CommunicationMethodsFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Candidate/MatchStatusFrequencyFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Candidate/MatchesFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/CandidateReferenceFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/CandidateApplicationsFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/MoneyRangeFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/SemanticSearchFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Industry.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/PositionEmail.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/NotesFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/ScheduledItemsFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/FolderGroupsFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/CustomField.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/SelectFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Attachment.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/ComplexRecruiterFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/OwnerType.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/Templates/ComplexRecruiterFilter.css", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Education/EducationFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/WorkHistory/WorkHistoryFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/ShiftsFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/VMS/VendorFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Candidate/AwrQualificationFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Candidate/CheckDeliveryMethods.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Skill/LiveSkillsFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/SavedShareableItemList/SavedSearchButton.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/FolderGroup.js", ENDITEM, 
		"Url=/Mvc/Content/js/Forms/Search/sidebarButton.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Components/LegacyCooltipButton.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/MarketingCampaign.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Components/ExportButton.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/SearchSidebarButtons/SendMessages.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Components/CompareResumeButton.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Requirement/AddRequirementSidebarButton.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Components/MailingListButton.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/MailingList.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Components/SimpleSidebarButtons.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Components/ScheduledItemButtons.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/ScheduledItem/QuickTaskSidebarButton.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/ScheduledItem/Templates/SearchSidebarButtons.css", ENDITEM, 
		"Url=/Mvc/Content/js/BL/SearchSidebarButtons/BulkUpdate.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Tags/common.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/DropDownFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Tags/TagView.js", ENDITEM, 
		"Url=/Mvc/Content/js/Localization/ResourceKeys.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Skill/Skill.js", ENDITEM, 
		"Url=/Mvc/Content/js/Currency/CurrencyService.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Address/Address.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/DateTimePicker.js", ENDITEM, 
		"Url=/Mvc/Currency/CurrencyModel", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Base/DeclareDataSource.js", ENDITEM, 
		"Url=/Mvc/Candidate/Statuses-all", ENDITEM, 
		"Url=/Mvc/DepartmentDimension/DimensionValues-all", ENDITEM, 
		"Url=/api/tags/getVisibleTags?aboutType=6", ENDITEM, 
		"Url=/Mvc/adSource/list-all?aboutType=6", ENDITEM, 
		"Url=/Mvc/adsource/allCategories", ENDITEM, 
		"Url=/Mvc/location/states-all", ENDITEM, 
		"Url=/Mvc/industry/list-all", ENDITEM, 
		"Url=/Mvc/ownership/ownerTypes-all", ENDITEM, 
		"Url=/Mvc/location/regions-all", ENDITEM, 
		"Url=/Mvc/Awr/GetQualificationPeriodDuration", ENDITEM, 
		"Url=/Mvc/currency/forLookup-all", ENDITEM, 
		"Url=/Mvc/Address/GetDefaultCountry", ENDITEM, 
		"Url=/Mvc/skill/all", ENDITEM, 
		"Url=/Mvc/match/statuses-all", ENDITEM, 
		"Url=/Mvc/match/Statuses-open", ENDITEM, 
		"Url=/Mvc/Daxtra/GetHtml?url=action%3Dsearch_interface%26style%3Ddivs%26libs%3Djb_params%2Cprototype%2Ccontrols%2Ceffects%2Ccss%26ajax_updater%3Dhttps%3A%2F%2Fstaff.belflex.com%2FMvc%2FDaxtra%2FAjaxUpdater%26ajax_auto_completer%3Dhttps%3A%2F%2Fstaff.belflex.com%2FMvc%2FDaxtra%2FAjaxCompleter&_=1583534192685", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Components/SimpleLinkSidebarButtons.js", ENDITEM, 
		"Url=/Mvc/Content/js/Forms/interfaces.js", ENDITEM, 
		"Url=/Mvc/Content/js/Values/Types/CLR/numericType.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/Slider.js", ENDITEM, 
		"Url=/Mvc/candidate/EducationLevels-all", ENDITEM, 
		"Url=/Mvc/candidate/ClearanceLevels-all", ENDITEM, 
		"Url=/Mvc/candidate/Ratings-all", ENDITEM, 
		"Url=/Mvc/candidate/ContractorTypes-all", ENDITEM, 
		"Url=/Mvc/candidate/CitizenshipTypes-all", ENDITEM, 
		"Url=/Mvc/candidate/RelocationRegions-all", ENDITEM, 
		"Url=/Mvc/candidate/DivisionMarkets-all", ENDITEM, 
		"Url=/Mvc/candidate/Requirements-all", ENDITEM, 
		"Url=/Mvc/candidate/RequirementTypes-all", ENDITEM, 
		"Url=/Mvc/requirement/Statuses-all", ENDITEM, 
		"Url=/Mvc/candidate/Assessments-all", ENDITEM, 
		"Url=/Mvc/Content/js/BL/User.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/FlagListControl.js", ENDITEM, 
		"Url=/Mvc/skill/Levels-all", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Company/Company.js", ENDITEM, 
		"Url=/Mvc/CommunicationMethods/AllCommunicationCategories", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Position/Position.js", ENDITEM, 
		"Url=/Mvc/CommunicationMethods/AllCommunicationtypes", ENDITEM, 
		"Url=/Mvc/Content/js/BL/NoteAction.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/ScheduledItem/ScheduledItem.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Department.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Shift.js", ENDITEM, 
		"Url=/Mvc/noteaction/List-all", ENDITEM, 
		"Url=/Mvc/Content/js/BL/ScheduledItem/Templates/ManageScheduledItem.css", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/PagedList.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/Knockout/knockout.mapping-latest.js", ENDITEM, 
		"Url=/Mvc/department/all", ENDITEM, 
		"Url=/Mvc/Content/js/Search/SavedShareableItemList/SavedShareableItemList.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Components/PopupSidebarButtonBase.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/SavedShareableItemList/Styles/SavedShareableItemList.css", ENDITEM, 
		"Url=/Mvc/CheckDeliveryMethod/List", ENDITEM, 
		"Url=/Mvc/folderGroup/all", ENDITEM, 
		"Url=/Mvc/folderGroup/allCategories", ENDITEM, 
		"Url=/Mvc/folderGroup/allSubcategories", ENDITEM, 
		"Url=/Mvc/folderGroup/getStatuses?aboutType=6", ENDITEM, 
		"Url=/Mvc/mailingList/List-all?currentUser=true", ENDITEM, 
		"Url=/Mvc/Content/js/Forms/sendSurveyDialog.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Tags/TagsSelector.js", ENDITEM, 
		"Url=/Mvc/Content/js/Forms/Templates/sendSurveyDialog.css", ENDITEM, 
		"Url=/Mvc/Content/js/BL/ScheduledItem/ScheduledItemModels.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/jQuery-plugins/jquery.numeric.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/jQuery-plugins/jquery.ui.numeric.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/Editor.js", ENDITEM, 
		"Url=/Mvc/Content/js/Search/Filters/ListRangeFilter.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Tasks/Sharing.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/ScheduledItem/ChoosePeople.js", ENDITEM, 
		"Url=/Mvc/forms/list-all", ENDITEM, 
		"Url=/Mvc/Content/js/Search/SavedShareableItemList/Actions.js", ENDITEM, 
		"Url=/Mvc/shift/Statuses-all", ENDITEM, 
		"Url=/Mvc/shift/CancellationReasons-all", ENDITEM, 
		"Url=/Mvc/shift/TravelStatuses-all", ENDITEM, 
		"Url=/Mvc/shift/FolderGroups-all", ENDITEM, 
		"Url=/Mvc/candidate/EndReasons-all", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Sharing/interfaces.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/SharedPopup.js", ENDITEM, 
		"Url=/Mvc/Content/js/Forms/designer.js", ENDITEM, 
		"Url=/Mvc/Content/js/Forms/Templates/designer.css", ENDITEM, 
		"Url=/Mvc/candidate/Statuses-all", ENDITEM, 
		"Url=/Mvc/Content/js/BL/Email/Template.js", ENDITEM, 
		"Url=/Mvc/Content/js/BL/AboutTypeLookup.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/MultiSelect.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/ReorderableList.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/Ace.js", ENDITEM, 
		"Url=/Mvc/Content/js/Controls/Lookup.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/Ace/mode-less.js", ENDITEM, 
		"Url=/Mvc/Content/js/External/Ace/ace.js", ENDITEM, 
		"Url=/Mvc/scheduledItem/AllTypes", ENDITEM, 
		"Url=/api/tags/getVisibleTags?aboutType=9", ENDITEM, 
		"Url=/Mvc/scheduledItem/getCategories?type=110&entityIDs=00000000-0000-0000-0000-000000000e01", ENDITEM, 
		"Url=/Mvc/Email/Templates-all", ENDITEM, 
		"Url=/Mvc/Content/Images/Icons/map.png", ENDITEM, 
		LAST);

	web_url("SearchResults.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Templates/SearchResults.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t125.inf", 
		"Mode=HTML", 
		LAST);

	web_url("InfoBox.html_2", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Controls/Templates/InfoBox.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t126.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Help.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Controls/Templates/Help.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t127.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Criterion.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Templates/Criterion.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t128.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/Mvc/Content/images/select2.png", "Referer=https://staff.belflex.com/Mvc/Content/css/Library/library.min.css", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/search/icon-menu.svg", "Referer=https://staff.belflex.com/Mvc/Content/css/erecruit.css", ENDITEM, 
		"Url=/Mvc/Content/js/External/Kendo/styles/Uniform/sprite.png", "Referer=https://staff.belflex.com/Mvc/Content/js/External/Kendo/styles/kendo.uniform.min.css", ENDITEM, 
		LAST);

	web_url("FtsFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/FtsFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t129.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Buttons.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Components/Templates/Buttons.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t130.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Columns.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Components/Templates/Columns.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t131.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Tip", 
		"URL=https://staff.belflex.com/Mvc/Help/Tip/?value=FullTextSearch.FilterUI", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t132.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Status.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/Status.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t133.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Filter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Tags/Templates/Filter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t134.inf", 
		"Mode=HTML", 
		LAST);

	web_url("DaxtraFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Daxtra/Templates/DaxtraFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t135.inf", 
		"Mode=HTML", 
		LAST);

	web_custom_request("set", 
		"URL=https://staff.belflex.com/Mvc/userSettings/set", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t136.inf", 
		"Mode=HTML", 
		"EncType=application/json", 
		"Body={\"BucketPath\":\"Search.Candidate.FullPage\",\"ContainerID\":\"Search.ParameterHistory\",\"Container\":{\"LastUsedParameters\":[\"Fts\",\"Status\",\"Tags\",\"dx\",\"Location\",\"Semantic\",\"Owner\"],\"RecentParameters\":[]}}", 
		LAST);

	web_url("TextFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/TextFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t137.inf", 
		"Mode=HTML", 
		LAST);

	web_url("RecruiterFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Templates/RecruiterFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t138.inf", 
		"Mode=HTML", 
		LAST);

	web_url("DateRangeFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/DateRangeFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t139.inf", 
		"Mode=HTML", 
		LAST);

	web_url("CheckboxFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/CheckboxFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t140.inf", 
		"Mode=HTML", 
		LAST);

	web_url("OwnershipMaintenanceTypeFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/OwnershipMaintenanceTypeFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t141.inf", 
		"Mode=HTML", 
		LAST);

	web_url("OwnershipExpirationFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/OwnershipExpirationFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t142.inf", 
		"Mode=HTML", 
		LAST);

	web_url("AdsourceFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Templates/AdsourceFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t143.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Location.SearchFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Templates/Location.SearchFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t144.inf", 
		"Mode=HTML", 
		LAST);

	web_url("DateFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/DateFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t145.inf", 
		"Mode=HTML", 
		LAST);

	web_url("filter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Forms/Search/Templates/filter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t146.inf", 
		"Mode=HTML", 
		LAST);

	web_url("SkillsFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Skill/Templates/SkillsFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t147.inf", 
		"Mode=HTML", 
		LAST);

	web_url("RequirementsFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Candidate/Templates/RequirementsFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t148.inf", 
		"Mode=HTML", 
		LAST);

	web_url("AssessmentsFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Candidate/Templates/AssessmentsFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t149.inf", 
		"Mode=HTML", 
		LAST);

	web_url("PastStatusFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/PastStatusFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t150.inf", 
		"Mode=HTML", 
		LAST);

	web_url("FlagListFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/FlagListFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t151.inf", 
		"Mode=HTML", 
		LAST);

	web_url("CommunicationMethodsFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/CommunicationMethodsFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t152.inf", 
		"Mode=HTML", 
		LAST);

	web_url("MatchStatusFrequencyFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Candidate/Templates/MatchStatusFrequencyFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t153.inf", 
		"Mode=HTML", 
		LAST);

	web_url("MatchesFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Candidate/Templates/MatchesFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t154.inf", 
		"Mode=HTML", 
		LAST);

	web_url("CandidateReferenceFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/CandidateReferenceFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t155.inf", 
		"Mode=HTML", 
		LAST);

	web_url("CandidateApplicationsFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/CandidateApplicationsFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t156.inf", 
		"Mode=HTML", 
		LAST);

	web_url("MoneyRangeFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/MoneyRangeFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t157.inf", 
		"Mode=HTML", 
		LAST);

	web_url("SemanticSearchFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/SemanticSearchFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t158.inf", 
		"Mode=HTML", 
		LAST);

	web_url("IndustryFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Templates/IndustryFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t159.inf", 
		"Mode=HTML", 
		LAST);

	web_url("PositionEmailFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/PositionEmailFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t160.inf", 
		"Mode=HTML", 
		LAST);

	web_url("NotesFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/NotesFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t161.inf", 
		"Mode=HTML", 
		LAST);

	web_url("ScheduledItemsFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/ScheduledItemsFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t162.inf", 
		"Mode=HTML", 
		LAST);

	web_url("FolderGroupsFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/FolderGroupsFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t163.inf", 
		"Mode=HTML", 
		LAST);

	web_url("CustomField.Search.SimpleRangeFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Templates/CustomField.Search.SimpleRangeFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t164.inf", 
		"Mode=HTML", 
		LAST);

	web_url("SelectFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/SelectFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t165.inf", 
		"Mode=HTML", 
		LAST);

	web_url("SelectFilter.WithExclusion.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/SelectFilter.WithExclusion.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t166.inf", 
		"Mode=HTML", 
		LAST);

	web_url("AttachmentFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Templates/AttachmentFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t167.inf", 
		"Mode=HTML", 
		LAST);

	web_url("ComplexRecruiterFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/ComplexRecruiterFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t168.inf", 
		"Mode=HTML", 
		LAST);

	web_url("ShiftsFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/ShiftsFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t169.inf", 
		"Mode=HTML", 
		LAST);

	web_url("EducationFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Education/Templates/EducationFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t170.inf", 
		"Mode=HTML", 
		LAST);

	web_url("WorkHistoryFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/WorkHistory/Templates/WorkHistoryFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t171.inf", 
		"Mode=HTML", 
		LAST);

	web_url("VendorFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/VMS/Templates/VendorFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t172.inf", 
		"Mode=HTML", 
		LAST);

	web_url("AwrQualificationFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Candidate/Templates/AwrQualificationFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t173.inf", 
		"Mode=HTML", 
		LAST);

	web_url("CheckDeliveryMethods.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Candidate/Templates/CheckDeliveryMethods.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t174.inf", 
		"Mode=HTML", 
		LAST);

	web_url("SavedSearchButton.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/SavedShareableItemList/Templates/SavedSearchButton.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t175.inf", 
		"Mode=HTML", 
		LAST);

	web_url("FolderGroup.MassManageButton.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Templates/FolderGroup.MassManageButton.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t176.inf", 
		"Mode=HTML", 
		LAST);

	web_url("sidebarButton.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Forms/Search/Templates/sidebarButton.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t177.inf", 
		"Mode=HTML", 
		LAST);

	web_url("LegacyCooltipButton.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Components/Templates/LegacyCooltipButton.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t178.inf", 
		"Mode=HTML", 
		LAST);

	web_url("MarketingCampaign.AddPeoplePopup.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Templates/MarketingCampaign.AddPeoplePopup.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t179.inf", 
		"Mode=HTML", 
		LAST);

	web_url("MarketingCampaign.AddPeopleSidebarButton.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Templates/MarketingCampaign.AddPeopleSidebarButton.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t180.inf", 
		"Mode=HTML", 
		LAST);

	web_url("ExportButton.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Components/Templates/ExportButton.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t181.inf", 
		"Mode=HTML", 
		LAST);

	web_url("CompareResumeButton.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Components/Templates/CompareResumeButton.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t182.inf", 
		"Mode=HTML", 
		LAST);

	web_url("AddRequirementSidebarButton.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Requirement/Templates/AddRequirementSidebarButton.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t183.inf", 
		"Mode=HTML", 
		LAST);

	web_url("MailingList.AddRecipientsSidebarButton.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Templates/MailingList.AddRecipientsSidebarButton.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t184.inf", 
		"Mode=HTML", 
		LAST);

	web_url("MailingListButton.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Components/Templates/MailingListButton.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t185.inf", 
		"Mode=HTML", 
		LAST);

	web_url("SimpleSidebarButtons.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Components/Templates/SimpleSidebarButtons.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t186.inf", 
		"Mode=HTML", 
		LAST);

	web_url("QuickTaskSidebarButton.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/ScheduledItem/Templates/QuickTaskSidebarButton.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t187.inf", 
		"Mode=HTML", 
		LAST);

	web_url("ScheduledItemButtons.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Components/Templates/ScheduledItemButtons.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t188.inf", 
		"Mode=HTML", 
		LAST);

	web_url("TagView.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Tags/Templates/TagView.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t189.inf", 
		"Mode=HTML", 
		LAST);

	web_url("DropDownFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Templates/DropDownFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t190.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Tip_2", 
		"URL=https://staff.belflex.com/Mvc/Help/Tip/?value=LocationSearch.FilterUI", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t191.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/Mvc/Content/images/bits/ddl.png", "Referer=https://staff.belflex.com/Mvc/Content/css/erecruit.css", ENDITEM, 
		LAST);

	web_url("DateTimePicker.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Controls/Templates/DateTimePicker.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t192.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Tip_3", 
		"URL=https://staff.belflex.com/Mvc/Help/Tip/?value=MatchStatusFrequencySearch.FilterUI", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t193.inf", 
		"Mode=HTML", 
		LAST);

	web_url("SimpleLinkSidebarButton.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Components/Templates/SimpleLinkSidebarButton.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t194.inf", 
		"Mode=HTML", 
		LAST);

	web_custom_request("set_2", 
		"URL=https://staff.belflex.com/Mvc/userSettings/set", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t195.inf", 
		"Mode=HTML", 
		"EncType=application/json", 
		"Body={\"BucketPath\":\"Search.Candidate.FullPage\",\"ContainerID\":\"Search.ParameterHistory\",\"Container\":{\"LastUsedParameters\":[\"Fts\",\"Status\",\"Tags\",\"dx\",\"Location\",\"Semantic\",\"Owner\"],\"RecentParameters\":[]}}", 
		LAST);

	web_url("ListSlider.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Controls/Templates/ListSlider.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t196.inf", 
		"Mode=HTML", 
		LAST);

	web_url("FlagListControl.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Controls/Templates/FlagListControl.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t197.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Tip_4", 
		"URL=https://staff.belflex.com/Mvc/Help/Tip/?value=CommunicationMethodSearch.FilterUI", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t198.inf", 
		"Mode=HTML", 
		LAST);

	web_url("DepartmentFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Templates/DepartmentFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t199.inf", 
		"Mode=HTML", 
		LAST);

	web_url("ManageScheduledItem.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/ScheduledItem/Templates/ManageScheduledItem.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t200.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Pager.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Controls/Templates/Pager.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t201.inf", 
		"Mode=HTML", 
		LAST);

	web_url("SavedShareableItemList.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/SavedShareableItemList/Templates/SavedShareableItemList.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t202.inf", 
		"Mode=HTML", 
		LAST);

	web_custom_request("set_3", 
		"URL=https://staff.belflex.com/Mvc/userSettings/set", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t203.inf", 
		"Mode=HTML", 
		"EncType=application/json", 
		"Body={\"BucketPath\":\"Search.Candidate.FullPage\",\"ContainerID\":\"Search.ParameterHistory\",\"Container\":{\"LastUsedParameters\":[\"Fts\",\"Status\",\"Tags\",\"dx\",\"Location\",\"Semantic\",\"Owner\"],\"RecentParameters\":[]}}", 
		LAST);

	web_url("sendSurveyDialog.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Forms/Templates/sendSurveyDialog.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t204.inf", 
		"Mode=HTML", 
		LAST);

	web_url("TagsSelector.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/Tags/Templates/TagsSelector.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t205.inf", 
		"Mode=HTML", 
		LAST);

	web_url("ListRangeFilter.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Search/Filters/Templates/ListRangeFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t206.inf", 
		"Mode=HTML", 
		LAST);

	web_url("ChoosePeople.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/BL/ScheduledItem/Templates/ChoosePeople.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t207.inf", 
		"Mode=HTML", 
		LAST);

	web_custom_request("set_4", 
		"URL=https://staff.belflex.com/Mvc/userSettings/set", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t208.inf", 
		"Mode=HTML", 
		"EncType=application/json", 
		"Body={\"BucketPath\":\"Search.Candidate.FullPage\",\"ContainerID\":\"Search.ParameterHistory\",\"Container\":{\"LastUsedParameters\":[\"Fts\",\"Status\",\"Tags\",\"dx\",\"Location\",\"Semantic\",\"Owner\"],\"RecentParameters\":[]}}", 
		LAST);

	web_url("designer.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Forms/Templates/designer.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t209.inf", 
		"Mode=HTML", 
		LAST);

	web_url("designer-field.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Forms/Templates/designer-field.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t210.inf", 
		"Mode=HTML", 
		LAST);

	web_url("designer-pageBreak.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Forms/Templates/designer-pageBreak.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t211.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/Mvc/Content/images/bits/jqueryui/ui-bg_highlight-soft_75_cccccc_1x100.png", "Referer=https://staff.belflex.com/Mvc/Content/css/Library/library.min.css", ENDITEM, 
		"Url=/Mvc/Content/images/bits/jqueryui/ui-bg_glass_75_e6e6e6_1x400.png", "Referer=https://staff.belflex.com/Mvc/Content/css/Library/library.min.css", ENDITEM, 
		LAST);

	web_url("MultiSelect.html", 
		"URL=https://staff.belflex.com/Mvc/Content/js/Controls/Templates/MultiSelect.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t212.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/Mvc/Content/images/bits/jqueryui/ui-bg_glass_65_ffffff_1x400.png", "Referer=https://staff.belflex.com/Mvc/Content/css/Library/library.min.css", ENDITEM, 
		LAST);

	web_custom_request("DesignerModel", 
		"URL=https://staff.belflex.com/Mvc/Forms/DesignerModel", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t213.inf", 
		"Mode=HTML", 
		"EncType=application/json", 
		"Body=null", 
		LAST);

	web_custom_request("set_5", 
		"URL=https://staff.belflex.com/Mvc/userSettings/set", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t214.inf", 
		"Mode=HTML", 
		"EncType=application/json", 
		"Body={\"BucketPath\":\"Search.Candidate.FullPage\",\"ContainerID\":\"Search.ParameterHistory\",\"Container\":{\"LastUsedParameters\":[\"Fts\",\"Status\",\"Tags\",\"dx\",\"Location\",\"Semantic\",\"Owner\"],\"RecentParameters\":[]}}", 
		EXTRARES, 
		"Url=../Content/fonts/fontawesome-webfont.woff2?v=4.4.0", "Referer=https://staff.belflex.com/Mvc/Content/css/Library/library.min.css", ENDITEM, 
		"Url=../User/CheckExpiration", "Referer=https://staff.belflex.com/Recruiter/", ENDITEM, 
		"Url=/mvc/dispatch/ping?connectionData=%5B%7B%22name%22%3A%22notification%22%7D%5D&_=1583533748747", "Referer=https://staff.belflex.com/Recruiter/", ENDITEM, 
		LAST);

	web_url("Tip_5", 
		"URL=https://staff.belflex.com/Mvc/Help/Tip/?value=SearchColumn.Candidate.Status", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t215.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/Mvc/Content/js/External/Kendo/styles/Uniform/loading-image.gif", "Referer=https://staff.belflex.com/Mvc/Content/js/External/Kendo/styles/kendo.uniform.min.css", ENDITEM, 
		LAST);

    web_reg_find("Text=Richardson", LAST);
	web_custom_request("Search-FetchData", 
		"URL=https://staff.belflex.com/Search/candidate/Search-FetchData", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com//Search/candidate/", 
		"Snapshot=t216.inf", 
		"Mode=HTML", 
		"EncType=application/json", 
		"Body={\"PageSize\":20,\"Page\":0,\"Criterion\":{\"IncludeDataSources\":[\"erecruit Internal Database\",\"Job Boards\"],\"Arguments\":[{\"DataSource\":\"erecruit Internal Database\",\"Parameter\":\"Fts\",\"Value\":{\"Query\":\"java\",\"SearchIndexes\":[],\"SearchRecord\":true,\"Stemming\":false,\"Thesaurus\":false}},{\"DataSource\":\"erecruit Internal Database\",\"Parameter\":\"Status\",\"Value\":{\"Statuses\":[31,32,33,34,38,44,46,47,48,49,50,51],\"DimensionValueID\":null,\"DimensionStatuses\""
		":null}},{\"DataSource\":\"erecruit Internal Database\",\"Parameter\":\"Industry\",\"Value\":{\"IndustryIds\":[]}}]},\"GridLayout\":{\"Columns\":[{\"ID\":\"DefaultResumeId\"},{\"ID\":\"Relevance\"},{\"ID\":\"Candidate\"},{\"ID\":\"Title\"},{\"ID\":\"CurrentEmployer\"},{\"ID\":\"FolderGroup\"},{\"ID\":\"Location\"},{\"ID\":\"Status\"}],\"Groups\":null,\"Sorters\":[{\"ID\":\"Relevance\",\"Direction\":1},{\"ID\":\"Candidate\",\"Direction\":0}],\"PageSize\":20,\"PageSizes\":[20,50,100,500,1000]}}", 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/statusicons/99.png", "Referer=https://staff.belflex.com/Mvc/Content/css/erecruit.css", ENDITEM, 
		LAST);
 

	lr_end_transaction("1_Candidate Search",LR_AUTO);

	lr_start_transaction("1_click on first result");

	web_url("manage.aspx", 
		"URL=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Recruiter/", 
		"Snapshot=t535.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/Telerik.Web.UI.WebResource.axd?_TSM_HiddenField_=ctl00_ctl00_radScriptManager_TSM&compress=1&_TSM_CombinedScripts_=%3b%3bSystem.Web.Extensions%2c+Version%3d4.0.0.0%2c+Culture%3dneutral%2c+PublicKeyToken%3d31bf3856ad364e35%3aen-US%3a92dc34f5-462f-43bd-99ec-66234f705cd1%3aea597d4b%3ab25378d2%3bTelerik.Web.UI%2c+Version%3d2013.1.220.40%2c+Culture%3dneutral%2c+"
		"PublicKeyToken%3d121fae78165ba3d4%3aen-US%3ad8ebf3de-0179-4fa4-89e6-a030e0cf94a1%3a16e4e7cd%3aed16cbdc%3a874f8ea2%3af7645509%3a24ee1bba%3af46195d3%3a19620875%3a39040b5c%3a6a6d718d%3ae330518b%3a1e771326%3a8e6f0d33%3a7165f74", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Services/UpdateService.asmx/js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("addrecent", 
		"URL=https://staff.belflex.com/api/bookmark/addrecent", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t536.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={\"abouttypeid\":6,\"referenceid\":2494772,\"name\":\"Kandasamy Java/j2ee Developer (2494772)\",\"userinfo\":\"%7b%22UserID%22%3a%2208b5c73d-8e4d-467c-82be-0c6789f8f6a5%22%2c%22EntityID%22%3a%2200000000-0000-0000-0000-000000000e01%22%2c%22LoggedInAsMode%22%3a1%2c%22TimeZone%22%3a%22Eastern+Standard+Time%22%7d\"}", 
		LAST);

	web_custom_request("GetWidgetWithSession", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidgetWithSession", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t537.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'tags/tags','data':'{\"AboutType\":\"Candidate\",\"ReferenceID\":2494772,\"LoggedInAsMode\":\"Recruiter\",\"CurrentUserID\":\"08b5c73d-8e4d-467c-82be-0c6789f8f6a5\",\"CurrentEntityID\":\"00000000-0000-0000-0000-000000000e01\",\"AdditionalData\":\"undefined\"}'}", 
		LAST);

	web_custom_request("GetWidget", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t538.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_1, 
		LAST);

	web_custom_request("GetWidget_2", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t539.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_2, 
		LAST);

	web_custom_request("GetWidget_3", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t540.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_3, 
		LAST);

	web_custom_request("GetWidget_4", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t541.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_4, 
		LAST);

	web_custom_request("GetWidget_5", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t542.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_5, 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/email.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("GetWidget_6", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t543.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_6, 
		LAST);

	web_custom_request("GetWidget_7", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t544.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_7, 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/abouttypes/6.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/calendar.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/webpage.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/note_add.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("GetWidgetWithSession_2", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidgetWithSession", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t545.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_8, 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/calendar_add.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/money.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/90.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/key_disabled.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("GetWidget_8", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t546.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'contactmethods','data':'{\"AboutType\":\"Candidate\",\"ReferenceID\":2494772,\"LoggedInAsMode\":\"Recruiter\",\"CurrentUserID\":\"08b5c73d-8e4d-467c-82be-0c6789f8f6a5\",\"CurrentEntityID\":\"00000000-0000-0000-0000-000000000e01\",\"AdditionalData\":\"%7B%20%27Name%27%3A%20%27Kandasamy+Java%252fj2ee+"
		"Developer%27%2C%20%27Email%27%3A%20%27%27%2C%20%27Address%27%3A%20%27eyJDb21tdW5pY2F0aW9uVHlwZSI6NDAwLCJTdGF0ZUNvZGUiOiJHQSIsIlN0YXRlTmFtZSI6Ikdlb3JnaWEiLCJDb3VudHJ5TmFtZSI6IlVuaXRlZCBTdGF0ZXMgb2YgQW1lcmljYSIsIlJlZ2lvbk5hbWUiOiIiLCJDb21tdW5pY2F0aW9uVHlwZUlkIjo0MDAsIk5hbWUiOiJNYWluIEFkZHJlc3MiLCJBZGRyZXNzSUQiOjYyNzI3ODUsIkFkZHJlc3NMaW5lMSI6IiIsIkFkZHJlc3NMaW5lMiI6IiIsIkNpdHkiOiJBbHBoYXJldHRhIiwiU3RhdGVJRCI6MTUsIkNvdW50cnlJRCI6MjIwLCJQb3N0YWxDb2RlIjoiMzAwMDQiLCJSZWdpb25JRCI6bnVsbH0%253d%27%2C%20%27A"
		"ddressID%27%3A%206272785%2C%20%27NrOfAddresses%27%3A%201%20%7D\"}'}", 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/apps/linkedin.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/disk.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/arrowjoin.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/position.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/task_add.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/check.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/printer.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("ManageCandidateAccrualSchedules", 
		"URL=https://staff.belflex.com/MVC/CandidateAccrualSchedule/ManageCandidateAccrualSchedules?candidateID=2494772", 
		"Method=GET", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t547.inf", 
		"Mode=HTML", 
		"EncType=application/x-www-form-urlencoded; charset=utf-8", 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/phone.png", "Referer=https://staff.belflex.com/MVC/Content/css/erecruit.css", ENDITEM, 
		"Url=/App_Themes/Default/javascript/jquery.validate.unobtrusive.js?_=1583777059215", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/sms.png", "Referer=https://staff.belflex.com/MVC/Content/css/erecruit.css", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/80.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/260.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/8.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/requirements.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/match.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/20.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/attachment.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/paid.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/270.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/12.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/candidatereference.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/3.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/email_ok.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/email_nok.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/phone_ok.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/phone_nok.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/sms_ok.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/sms_nok.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/print.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("GetWidget_9", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t548.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'address/address','data':'{\"AboutType\":\"Candidate\",\"ReferenceID\":2494772,\"LoggedInAsMode\":\"Recruiter\",\"CurrentUserID\":\"08b5c73d-8e4d-467c-82be-0c6789f8f6a5\",\"CurrentEntityID\":\"00000000-0000-0000-0000-000000000e01\",\"AdditionalData\":\""
		"%7B%20%27Address%27%3A%20%27eyJDb21tdW5pY2F0aW9uVHlwZSI6NDAwLCJTdGF0ZUNvZGUiOiJHQSIsIlN0YXRlTmFtZSI6Ikdlb3JnaWEiLCJDb3VudHJ5TmFtZSI6IlVuaXRlZCBTdGF0ZXMgb2YgQW1lcmljYSIsIlJlZ2lvbk5hbWUiOiIiLCJDb21tdW5pY2F0aW9uVHlwZUlkIjo0MDAsIk5hbWUiOiJNYWluIEFkZHJlc3MiLCJBZGRyZXNzSUQiOjYyNzI3ODUsIkFkZHJlc3NMaW5lMSI6IiIsIkFkZHJlc3NMaW5lMiI6IiIsIkNpdHkiOiJBbHBoYXJldHRhIiwiU3RhdGVJRCI6MTUsIkNvdW50cnlJRCI6MjIwLCJQb3N0YWxDb2RlIjoiMzAwMDQiLCJSZWdpb25JRCI6bnVsbH0%253d%27%2C%20%27AddressID%27%3A%206272785%2C%20%27NrOfAddr"
		"esses%27%3A%201%20%20%20%7D\"}'}", 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/positionmatching.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/tax.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/time.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("GetWidgetWithSession_3", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidgetWithSession", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t549.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'communicationlist','data':'{\"AboutType\":\"Candidate\",\"ReferenceID\":2494772,\"LoggedInAsMode\":\"Recruiter\",\"CurrentUserID\":\"08b5c73d-8e4d-467c-82be-0c6789f8f6a5\",\"CurrentEntityID\":\"00000000-0000-0000-0000-000000000e01\",\"AdditionalData\":\"%7B%20Mode%3A%20%27Sidebar%27%2C%20%27Email%27%20%3A%20%27%27%2C%20%27FullName%27%20%3A%20%27Kandasamy%20Java%252fj2ee%20Developer%27%20%20%7D\"}'}", 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/date.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/form.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/OnboardingIntegration/OnboardingMenu.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/RightBarSettings/RightBarSettings.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/Base/autobind.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/edit.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/Controls/Help.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/info.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/house.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/14/edit.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/14/houses.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/14/link.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/profile.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/communicationtypes/3.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/communicationtypes/2.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/communicationtypes/7.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/communicationtypes/1.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("OnboardingMenu.html", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/OnboardingIntegration/Templates/OnboardingMenu.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t550.inf", 
		"Mode=HTML", 
		LAST);

	web_url("Help.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Controls/Templates/Help.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t551.inf", 
		"Mode=HTML", 
		LAST);

	web_url("InfoBox.html_3", 
		"URL=https://staff.belflex.com/MVC/Content/js/Controls/Templates/InfoBox.html", 
		"TargetFrame=", 
		"Resource=0", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t552.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/Base/dataSource.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Localization/LocalizationModel", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=../Select.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/OnboardingIntegration/interfaces.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/Awr/BreakInServiceLog.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/Awr/QualifyingPeriodCounter.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/api/onboarding/AllCancellationReasons?OnboardingType=1", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("get", 
		"URL=https://staff.belflex.com/Mvc/userSettings/get", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t553.inf", 
		"Mode=HTML", 
		"EncType=application/json", 
		"Body={\"BucketPath\":\"RightBar.notes_sectioncontact_sectionrelated_sectionactions_sectionother_section\",\"ContainerID\":\"RightBar.SectionsOrder\"}", 
		LAST);

	web_url("BreakInServiceLog.html", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Awr/Templates/BreakInServiceLog.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t554.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/BL/Tags/TagsView.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("QualifyingPeriodCounter.html", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Awr/Templates/QualifyingPeriodCounter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t555.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/BL/Candidate/CandidateReview.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("get_2", 
		"URL=https://staff.belflex.com/Mvc/userSettings/get", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t556.inf", 
		"Mode=HTML", 
		"EncType=application/json", 
		"Body={\"BucketPath\":\"RightBar.notes_sectioncontact_sectionrelated_sectionactions_sectionother_section\",\"ContainerID\":\"RightBar.CollapsedSections\"}", 
		EXTRARES, 
		"Url=/MVC/Content/js/Search/EmbeddedSearch.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("TagsView.html", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Tags/Templates/TagsView.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t557.inf", 
		"Mode=HTML", 
		LAST);

	web_url("TagsGridCell.html", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Tags/Templates/TagsGridCell.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t558.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/BL/Awr/Events.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("CandidateReviewsList.html", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Candidate/Templates/CandidateReviewsList.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t559.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/BL/Tags/common.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/Tags/TagView.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/External/Knockout/knockout.mapping-latest.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/Currency/CurrencyService.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/Values/Types/CLR/numericType.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("TagView.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Tags/Templates/TagView.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t560.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/Mvc/Currency/CurrencyModel", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/currency/forLookup-all", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/delete.png", "Referer=https://staff.belflex.com/MVC/Content/css/erecruit.css", ENDITEM, 
		"Url=/MVC/Content/js/Search/SearchResults.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/CandidateReview/GetByCandidateId/?id=2494772", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("SearchResults.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Search/Templates/SearchResults.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t561.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=../Criterion.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=../LiveFilterService.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("Criterion.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Search/Templates/Criterion.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t562.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/External/Kendo/js-debug/kendo.web.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Search/Awr/By/BreakInService?candidateID=2494772", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Search/Awr/By/QualifyingPeriodCounter?candidateID=2494772", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=../Components/Columns.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("Columns.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Search/Components/Templates/Columns.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t563.inf", 
		"Mode=HTML", 
		LAST);

	web_url("crx", 
		"URL=https://clients2.google.com/service/update2/crx?os=win&arch=x64&os_arch=x86_64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=80.0.3987.132&lang=en-US&acceptformat=crx3&x=id%3Daknpkdffaafgjchaibgeefbgmgeghloj%26v%3D0.0.0.0%26installedby%3Dinternal%26uc%26ping%3Dr%253D2%2526e%253D0%2526dr%253D1&x=id%3Dmgndgikekgjfcpckkfioiadnlibdjbkf%26v%3D0.0.0.0%26installedby%3Dinternal%26uc&x="
		"id%3Dfdmmgilgnpjigdojojpjoooidkmcomcm%26v%3D0.0.0.0%26installedby%3Dinternal%26uc%26ping%3Dr%253D2%2526e%253D1&x=id%3Dmhbpoeinkhpajikalhfpjjafpfgjnmgk%26v%3D0.0.0.0%26installedby%3Dinternal%26uc%26ping%3Dr%253D2%2526e%253D0%2526dr%253D1", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/xml", 
		"Referer=", 
		"Snapshot=t564.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=https://staff.belflex.com/MVC/Content/js/BL/ScheduledItem/ScheduledItem.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=https://staff.belflex.com/MVC/Content/js/BL/ScheduledItem/Templates/ManageScheduledItem.css", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	lr_end_transaction("1_click on first result",LR_AUTO);

	lr_start_transaction("1_Add Note");

	web_url("ManageScheduledItem.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/ScheduledItem/Templates/ManageScheduledItem.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t565.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/Controls/DateTimePicker.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/Controls/Editor.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("DateTimePicker.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Controls/Templates/DateTimePicker.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t566.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/BL/User.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/Tags/TagsSelector.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/Tasks/Sharing.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/ScheduledItem/ScheduledItemModels.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/ScheduledItem/ChoosePeople.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("TagsSelector.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Tags/Templates/TagsSelector.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t567.inf", 
		"Mode=HTML", 
		LAST);

	web_url("ChoosePeople.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/ScheduledItem/Templates/ChoosePeople.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t568.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/Search/Filters/SelectFilter.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("SelectFilter.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Search/Filters/Templates/SelectFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t569.inf", 
		"Mode=HTML", 
		LAST);

	web_url("SelectFilter.WithExclusion.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Search/Filters/Templates/SelectFilter.WithExclusion.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t570.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/Controls/MultiSelect.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("MultiSelect.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Controls/Templates/MultiSelect.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t571.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/Search/DropDownFilter.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("DropDownFilter.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Search/Templates/DropDownFilter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t572.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/Controls/Lookup.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/api/tags/getVisibleTags?aboutType=9", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/ScheduledItem/ItemOptions?AboutType=Candidate&ReferenceID=2494772&FromFile=&FromAboutTypeID=&FromReferenceID=&EntityIDs%5B%5D=00000000-0000-0000-0000-000000000e01&TypeID=0&ItemID=0", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/user/List-getById?ids=08b5c73d-8e4d-467c-82be-0c6789f8f6a5&kinds=0&isActiveRecruitersOnly=true&useEntity=true", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/ScheduledItem/DistributionListValues", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/images/bits/cleditor/toolbar.gif", "Referer=https://staff.belflex.com/MVC/Content/css/Library/library.min.css", ENDITEM, 
		"Url=/MVC/Content/images/bits/cleditor/buttons.gif", "Referer=https://staff.belflex.com/MVC/Content/css/Library/library.min.css", ENDITEM, 
		"Url=/Mvc/Content/images/icons/puzzle.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("GetWidgetWithSession_4", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidgetWithSession", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t573.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'referencelist','data':'{\"LoggedInAsMode\":\"Recruiter\",\"CurrentUserID\":\"08b5c73d-8e4d-467c-82be-0c6789f8f6a5\",\"CurrentEntityID\":\"00000000-0000-0000-0000-000000000e01\",\"AdditionalData\":\""
		"%7B%20%20AllowEdit%3Atrue%2C%20CallerID%3A%20%27notereferences_manageScheduledItemWidget_773426%27%2C%20StartingReferences%3A%20%27%255B%257B%2522AboutType%2522%253A6%252C%2522ReferenceID%2522%253A%25222494772%2522%252C%2522IsPermanent%2522%253Atrue%252C%2522Name%2522%253A%2522Kandasamy%2520Java%252Fj2ee%2520Developer%2522%257D%255D%27%7D%20\"}'}", 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/abouttypes/7.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/2.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/scheduleditemtypes/110.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/ScheduledItem/DistributionListValues", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/images/bits/jqueryui/ui-bg_highlight-soft_75_cccccc_1x100.png", "Referer=https://staff.belflex.com/MVC/Content/css/Library/library.min.css", ENDITEM, 
		"Url=/MVC/Content/images/bits/jqueryui/ui-bg_glass_65_ffffff_1x400.png", "Referer=https://staff.belflex.com/MVC/Content/css/Library/library.min.css", ENDITEM, 
		"Url=/MVC/Content/images/bits/jqueryui/ui-bg_glass_75_e6e6e6_1x400.png", "Referer=https://staff.belflex.com/MVC/Content/css/Library/library.min.css", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/priorities/2.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/arrowright.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/arrowleft.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/bullet_delete.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	lr_end_transaction("1_Add Note",LR_AUTO);
 

	lr_start_transaction("1_save note");

	web_custom_request("AddFullNote", 
		"URL=https://staff.belflex.com/Mvc/ScheduledItem/AddFullNote", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t574.inf", 
		"Mode=HTML", 
		"EncType=application/json", 
		"Body={\"WithItem\":false,\"ItemID\":null,\"References\":[{\"AboutType\":6,\"ReferenceID\":\"2494772\",\"IsPermanent\":true,\"Name\":\"Kandasamy Java/j2ee Developer\"}],\"DefaultReferenceAboutType\":6,\"DefaultReference\":{\"ReferenceID\":\"2494772\",\"AboutType\":6},\"Assignee\":{\"PoolInstanceName\":null,\"Id\":877465},\"NoteNotifyOptions\":{\"SelectedDepartments\":[],\"SelectedDistributionLists\":[],\"SelectedExternalAboutTypes\":[],\"SelectedOwnerAboutTypes\":[],\"SelectedPeople\":[],\""
		"SelectedSpecialPeople\":[],\"SelectedSpecialPeopleIDs\":[]},\"ToRecipients\":{\"SelectedDepartments\":[],\"SelectedDistributionLists\":[],\"SelectedExternalAboutTypes\":[],\"SelectedOwnerAboutTypes\":[],\"SelectedPeople\":[],\"SelectedSpecialPeople\":[],\"SelectedSpecialPeopleIDs\":[]},\"Sharings\":[],\"TypeID\":0,\"CategoryID\":null,\"Priority\":2,\"Title\":null,\"Location\":null,\"ExportToCalendar\":false,\"Description\":null,\"FollowUpAction\":0,\"FollowUpTimeSpan\":{},\"FollowUpTitle\":null,\""
		"SetAsCompleted\":false,\"SetAsCanceled\":false,\"CreateNewTask\":false,\"PushForward\":false,\"FollowUpSkipWeekends\":false,\"RelatedAttachments\":[],\"Tags\":[],\"CreationStrategy\":null,\"BreakByAboutType\":6,\"Start\":\"3/9/2020 12:00 AM\",\"End\":\"3/9/2020 1:00 AM\",\"NoteOptions\":{\"ShareOptions\":[{\"AboutType\":7,\"DisplayName\":\"Internal users\",\"Selected\":true,\"IsEditable\":false},{\"AboutType\":6,\"DisplayName\":\"Referenced candidate(s)\",\"Selected\":false,\"IsEditable\":true},{"
		"\"AboutType\":20,\"DisplayName\":\"Vendor Managers\",\"Selected\":false,\"IsEditable\":true},{\"AboutType\":2,\"DisplayName\":\"Referenced contact(s)\",\"Selected\":false,\"IsEditable\":true}],\"Body\":\"asdasdasd\"}}", 
		LAST);

	web_custom_request("GetWidgetWithSession_5", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidgetWithSession", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t575.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'notelist','data':'eyJBYm91dFR5cGUiOiJDYW5kaWRhdGUiLCJSZWZlcmVuY2VJRCI6IjI0OTQ3NzIiLCJMb2dnZWRJbkFzTW9kZSI6IlJlY3J1aXRlciIsIkN1cnJlbnRVc2VySUQiOiIwOGI1YzczZC04ZTRkLTQ2N2MtODJiZS0wYzY3ODlmOGY2YTUiLCJDdXJyZW50RW50aXR5SUQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDBlMDEiLCJNb2RlIjoiU2lkZWJhciIsIlNob3dUaXRsZSI6IkZhbHNlIiwiU2hvd1JlZmVyZW5jZXMiOiJGYWxzZSJ9'}", 
		LAST);

    web_reg_find("Text=asdasd", LAST);
	web_custom_request("GetWidgetWithSession_6", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidgetWithSession", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t576.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'notelist','data':'eyJBYm91dFR5cGUiOiJDYW5kaWRhdGUiLCJSZWZlcmVuY2VJRCI6IjI0OTQ3NzIiLCJMb2dnZWRJbkFzTW9kZSI6IlJlY3J1aXRlciIsIkN1cnJlbnRVc2VySUQiOiIwOGI1YzczZC04ZTRkLTQ2N2MtODJiZS0wYzY3ODlmOGY2YTUiLCJDdXJyZW50RW50aXR5SUQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDBlMDEiLCJNb2RlIjoiU2lkZWJhciIsIlNob3dUaXRsZSI6IkZhbHNlIiwiU2hvd1JlZmVyZW5jZXMiOiJGYWxzZSJ9'}", 
		LAST); 

	lr_end_transaction("1_save note",LR_AUTO);
	return 0;
}